### ISSUE TITLE
move co-body to @cojs group

### ISSUE THREAD

**Issue by fengmk2** [cojs/co-body#17]
It will be better to make co-body keep update on @cojs https://github.com/cojs

/cc @tj

**Comment by fengmk2** [comment]
And we can handle these pr https://github.com/tj/co-body/pulls quickly.

**Comment by fixe** [comment]
+1.

**Comment by tj** [comment]
done

**Comment by fengmk2** [comment]
Thanks @tj

**Comment by fengmk2** [comment]
All pr merged. @tj can you add me to the authors list on npm? I want to publish a minor version `1.1.0`.

**Comment by tj** [comment]
added!

**Comment by fengmk2** [comment]
:+1: again! co-body@1.1.0 publish now!
