### ISSUE TITLE
add a strict mode: throw when json-body is non-object

### ISSUE THREAD

**Issue by dead-horse** [cojs/co-body#22]
[rfc4627](https://www.ietf.org/rfc/rfc4627.txt)
also see https://github.com/koajs/bodyparser/issues/19#issuecomment-98367747.

**Comment by dead-horse** [comment]
or make it configuable like https://github.com/expressjs/body-parser#strict

**Comment by coderhaoxin** [comment]
+1 for configuable, also default to `strict: true`.

**Comment by dead-horse** [comment]
sorry.
[rfc4627](https://tools.ietf.org/html/rfc4627) is rewrited by [rfc7159](https://tools.ietf.org/html/rfc7159)

```
JSON-text = ws value ws
```

but it is still good to have a strict mod for user-friendly
