### ISSUE TITLE
`qs` dependency update

### ISSUE THREAD

**Issue by pepkin88** [cojs/co-body#32]
Please update `qs` to the latest version, or at least to 5.0.0, where https://github.com/hapijs/qs/issues/114 was fixed.

**Comment by coderhaoxin** [comment]
cc @fengmk2 @dead-horse

**Comment by fengmk2** [comment]
@pepkin88 pr welcome

**Comment by fengmk2** [comment]
>= 4.1.0 can support custom qs module now. https://github.com/cojs/co-body/commit/3b9f8067b1c3e4d2e992154bafe88448d987aac3
