### ISSUE TITLE
"Strict" Option for JSON does not work

### ISSUE THREAD

**Issue by alqu** [cojs/co-body#45]
Hi,

I noticed that there is a bug in here: https://github.com/cojs/co-body/blob/master/lib/json.js#L50

It should be
`if (!strict) return str;`
instead of
`if (!strict) return str ? JSON.parse(str) : str;`

Please fix :-)

**Comment by alqu** [comment]
...or: does it mean: "if we have no strict mode setting, then -if the string is somewhat trueish - parse it?

Then I did not understand the logic in the first place.

**Comment by dead-horse** [comment]
strict mode will ensure `this.request.body` always be an object.
