### ISSUE TITLE
default compression algorithm in text parsing

### ISSUE THREAD

**Issue by felixsanz** [cojs/co-body#51]
Text.js contains `return raw(inflate(req), opts);`

https://github.com/cojs/co-body/blob/master/lib/text.js#L32

Why? I mean, there are other compressions algorithms apart from `inflate`. I'm using brotli and this parser is trying to inflate with zlib, so i'm getting an error

**Comment by bminer** [comment]
It's not trying to inflate using zlib. It just choked because "content-encoding: brotli" is unsupported by the inflate lib

**Comment by felixsanz** [comment]
@bminer inflation is made using zlib. It's a method on zlib. Brotli will be never supported on the inflation lib (i guess), because inflation is an algorithm that has nothing to do with brotli.
